version: '2.3'
services:
  experiment:
    tty: true
    ports: ['8888:8888']
    runtime: nvidia
    volumes: ['..:/app']
    build: {context: ., dockerfile: gpu.Dockerfile}
    image: learning-sensitive-representations
